import {Inter} from "next/font/google";
import "./globals.css";

import Providers from "./providers";
import {Suspense} from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({children}) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <Suspense
               fallback={
                  <div className="flex flex-col items-center justify-center min-h-screen py-2">
                     <h1 className="text-6xl font-bold text-red-700">Loading...</h1>
                  </div>
               }
            >
               <Providers>{children}</Providers>
            </Suspense>
         </body>
      </html>
   );
}
